# Generated by Django 4.0.5 on 2022-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
